[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_lottery = "9LzqYFW6Bx9D61fHicdnWgtjzwadHTGT2rFvuuSYkFM1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


